language: node_js
node_js: '10.16.3'
branches:
  only:
  - master
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist-demo
  verbose: true
  on:
    branch: master
